# Generated by Django 4.2.7 on 2023-12-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_employee', 'Can view employees'), ('can_manage_employee', 'Can manage employees')]},
        ),
    ]
