# Generated by Django 4.2.7 on 2023-12-01 10:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('permission', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
