# Generated by Django 4.2.7 on 2023-12-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_managers_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managers',
        ),
    ]
